import { Navigate, Route, Routes } from "react-router-dom";

import { useHealth } from "./api";
import AppShell from "./components/AppShell";
import EpicRiskPage from "./features/epic-risk/EpicRiskPage";
import HygienePage from "./features/hygiene/HygienePage";
import LeaderboardPage from "./features/leaderboard/LeaderboardPage";
import LeavesPage from "./features/leaves/LeavesPage";
import ProjectDetailPage from "./features/projects/ProjectDetailPage";
import ProjectsMonitoringPage from "./features/projects/ProjectsMonitoringPage";
import ProjectsPage from "./features/projects/ProjectsPage";
import SprintHealthPage from "./features/sprint-health/SprintHealthPage";
import Debug from "./pages/Debug";
import SettingsPage from "./pages/Settings";
import Setup from "./pages/Setup";

function PlaceholderPage({ tag, name, blurb }: { tag: string; name: string; blurb: string }) {
  return (
    <div>
      <h1 style={{ marginTop: 0 }}>
        {name}{" "}
        <span
          style={{
            fontSize: 12,
            verticalAlign: "middle",
            color: "var(--color-text-muted)",
            background: "rgba(0,0,0,0.05)",
            padding: "2px 8px",
            borderRadius: 999,
          }}
        >
          {tag}
        </span>
      </h1>
      <p style={{ color: "var(--color-text-muted)" }}>{blurb}</p>
    </div>
  );
}

export default function App() {
  const { data, isLoading } = useHealth();

  if (isLoading) {
    return (
      <main style={{ padding: 24, fontFamily: "var(--font-stack)" }}>Loading…</main>
    );
  }

  // Pre-setup: route everything except /setup itself to /setup
  if (data && !data.configured) {
    return (
      <Routes>
        <Route path="/setup" element={<Setup />} />
        <Route path="*" element={<Navigate to="/setup" replace />} />
      </Routes>
    );
  }

  return (
    <Routes>
      <Route path="/setup" element={<Setup />} />
      <Route
        path="*"
        element={
          <AppShell>
            <Routes>
              <Route path="/" element={<Navigate to="/debug" replace />} />
              <Route path="/debug" element={<Debug />} />
              <Route path="/sprint-health" element={<SprintHealthPage />} />
              <Route path="/epic-risk" element={<EpicRiskPage />} />
              <Route path="/hygiene" element={<HygienePage />} />
              <Route path="/leaves" element={<LeavesPage />} />
              <Route path="/projects" element={<ProjectsPage />} />
              <Route
                path="/projects/monitoring"
                element={<ProjectsMonitoringPage />}
              />
              <Route path="/projects/:name" element={<ProjectDetailPage />} />
              <Route path="/leaderboard" element={<LeaderboardPage />} />
              <Route
                path="/insights"
                element={
                  <PlaceholderPage
                    tag="v3"
                    name="Insights"
                    blurb="Weekly natural-language summary of velocity drift, scope-churn outliers, and carry-over patterns — generated by Claude from the local DB. Nothing leaves the machine without a click. Deferred until v1 is stable. See docs/local-app/10-roadmap-v3.md → v3-C."
                  />
                }
              />
              <Route path="/settings" element={<SettingsPage />} />
              <Route path="*" element={<Navigate to="/debug" replace />} />
            </Routes>
          </AppShell>
        }
      />
    </Routes>
  );
}
